# Generated by Django 5.1.4 on 2025-01-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='content',
            field=models.TextField(default='default_content', help_text='The data encoded in the QR code (e.g., URL or unique identifier).'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
